/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.4.1/userguide/multi_project_builds.html
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
        jcenter()
    }
}

rootProject.name = "kotlin-workshop"

include("kotlin-basic")
include("kotlin-coroutines")
include("kotlin-dagger-example")

include("spring-data:jdbc")
include("spring-data:jpa")

include("spring-boot:webflux")
include("spring-boot:webmvc")
include("spring-boot:route")

include("kotlin-tests")