logging.level.org.springframework.data: INFO
logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG

spring:
    jooq:
        sql-dialect: h2
    
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem:test;MVCC=true;
            driver-class-name: org.h2.Driver
            username: sa
            password: 
