package io.github.debop.springdata.jpa.mapping.onetoone

import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType.IDENTITY
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.OneToOne

@Repository
interface OneToOneUserRepository : JpaRepository<User, Long>

@Repository
interface OneToOneAddressRepository : JpaRepository<Address, Long>

/*
    User - Address 관계에서 Master 인 User가 Detail의 FK를 가지고 있다.
    이런 경우는 그냥 @ManyToOne 을 사용하는 것이 낫다
 */
/*
    create table onetoone_user (
       id bigint generated by default as identity,
        admin varchar(255),
        email varchar(255),
        firstname varchar(255),
        lastname varchar(255),
        password varchar(255),
        ranking varchar(255),
        username varchar(255),
        shipping_address_id bigint,         // address id 를 User 가 가진다.
        primary key (id)
    )

    create table onetoone_address (
       id bigint generated by default as identity,
        city varchar(255),
        street varchar(255),
        zipcode varchar(255),
        primary key (id)
    )

    alter table onetoone_user
       add constraint FKiby23vn74gp0itljopw918qjw
       foreign key (shipping_address_id)
       references onetoone_address
 */
@Entity(name = "onetoone_user")
data class User(var username: String) {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    var id: Long? = null

    var password: String? = null

    var firstname: String? = null
    var lastname: String? = null
    var email: String? = null
    var ranking: String? = null
    var admin: String? = null

    // LAZY 라 하더라도 EAGER로 로딩합니다.
    @OneToOne
    @JoinColumn(name = "shipping_address_id")
    var shippingAddress: Address? = null
}

@Entity(name = "onetoone_address")
data class Address(
    var street: String? = null,
    var city: String? = null,
    var zipcode: String? = null
) {
    @Id
    @GeneratedValue(strategy = IDENTITY)
    var id: Long? = null
}


